# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cdb9438214f2c4edc58e9e3eb993edb6f47326e67528b87429693246c9cc3901ac1bc060c2692e12b280e41ae3555f01793e476d1136e31d6ca05696074145c

test:
  secret_key_base: 1abb08da2c44cc67a4c121c8c0be6e181efc5946e417b7bae22c94fecda7e3f04cb2ec43629d6d34f921cd23435210198a4df3cd15cfc4ac113bba5fc4f0177c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
